name: "Update flakes"
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "30 18 * * 1"

jobs:
  update-flakes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      pull-requests: write
    steps:
      - name: Free disk space
        uses: easimon/maximize-build-space@v6
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true

      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Install Cachix
        uses: cachix/cachix-action@v12
        with:
          name: andrestylianos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Set priority flag for Cachix"
        run: nix-env --set-flag priority 0 cachix

      - name: Build old NixOS
        run: |
          nix build -o /tmp/old_system .#nixosConfigurations.uruk.config.system.build.toplevel

      - name: Update flake.nix
        run: |
          nix flake update

      - name: Build new NixOS
        run: |
          nix build -o /tmp/new_system .#nixosConfigurations.uruk.config.system.build.toplevel

      - name: Get NixOS diff
        id: get-pr-body
        run: |
          nix run github:NixOS/nixpkgs/nixos-unstable#nvd -- --color never diff /tmp/old_system /tmp/new_system > /tmp/pr-body.txt
          body=$(cat /tmp/pr-body.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "body=${body}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          body: |
            # NixOS changes:

            ```bash
            ${{ steps.get-pr-body.outputs.body }}
            ```
          commit-message: Update flake lock
          title: Update flake.nix
          assignees: andrestylianos
          branch: update-flake-nix
